# Generated by Django 5.1.6 on 2025-02-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_2_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_2', models.CharField(max_length=200)),
                ('description_2', models.TextField(blank=True)),
                ('done_2', models.BooleanField(default=False)),
            ],
        ),
    ]
