# Generated by Django 5.1.6 on 2025-02-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tasks', '0002_task_2_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_2_class',
            name='prueba',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
