# Generated by Django 5.1.5 on 2025-02-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_of_myfirstproyect', '0002_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
