# Generated by Django 5.1.5 on 2025-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_of_myfirstproyect', '0005_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='app_of_myfirstproyect.author'),
        ),
    ]
