# Generated by Django 5.1.5 on 2025-02-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Nombre'),
        ),
    ]
